#!/usr/bin/env python3
import sys
import lancedb
from lancedb.pydantic import LanceModel, Vector
from lancedb.embeddings import get_registry
from output import *
from rag_common import *

def syntax():
    print("Usage: rag_query.py <query>")
    sys.exit(1)

if len(sys.argv) < 2:
    syntax()

model = get_registry().get(embed_provider).create(name=embed_model, host=model_host)

# define the schema
class DecompilationPair(LanceModel):
    # This stores the ASM. 'SourceField' tells LanceDB to vectorize this text.
    asm_code: str = model.SourceField()
    # This stores the C. We don't necessarily need to vectorize the C, 
    # just retrieve it as a "Payload".
    c_code: str
    # The vector itself (automatically generated by LanceDB using nomic)
    vector: Vector(model.ndims()) = model.VectorField()

query = sys.argv[1]
limit = int(sys.argv[2]) if len(sys.argv) > 2 else 3
print(f"Querying for '{query}' with a limit of {limit}")
db = lancedb.connect(db_name)
table = db.open_table(table_name)
actual = table.search(query).limit(limit).to_pydantic(DecompilationPair)
i = 0
for a in actual:
    i += 1
    print(f"=== Sample {i}")
    print(f"/*\n{a.asm_code}*/")
    print(a.c_code, end='')

# .limit(3) gets the top 3 closest matches
#results = table.search(query_asm).limit(3).to_list()

# 4. Display the results
#for i, res in enumerate(results):
#    print(f"\n--- Match #{i+1} (Score: {res['_distance']:.4f}) ---")
#    print(f"Function: {res['function_name']}")
#    print(f"Reconstructed C:\n{res['c_code']}")