#!/usr/bin/env python3
import lancedb
import sys
from lancedb.pydantic import LanceModel, Vector
from lancedb.embeddings import get_registry
from output import *

setDebug(True)

def syntax():
    print("Syntax: rag_index.py <input_file>")
    sys.exit(1)

if len(sys.argv) != 2:
    syntax()

input_file = sys.argv[1]
info(f"Loading samples from {input_file}")

def add_sample(samples, asm_code, c_code):
    if asm_code and c_code:
        debug(f"Appending code to code_samples: asm:\n{asm_code}c:\n{c_code}", end='')
        samples.append({"asm_code": asm_code, "c_code": c_code})

# extract code samples from the input file
code_samples = []
with open(input_file, "r") as file:
    in_asm = False
    asm_code = ''
    c_code = ''
    for line in file:
        line_stripped = line.strip()
        if not line_stripped:
            # ignore empty lines
            continue
        elif line_stripped == '/*':
            # beginning of comment block, assembly code follows 
            # add previous code to code_samples if any 
            add_sample(code_samples, asm_code, c_code)
            asm_code = ''
            c_code = ''
            in_asm = True
        elif line_stripped == '*/':
            # end of comment block, c code follows
            in_asm = False
        elif in_asm:
            debug(f"Appending assembly code to asm_code: {line_stripped}")
            asm_code += line
        else:
            debug(f"Appending c code to c_code: {line_stripped}")
            c_code += line
    # final item after eof
    add_sample(code_samples, asm_code, c_code)

info(f"Loaded {len(code_samples)} samples")

# choose embedding model
model = get_registry().get("ollama").create(name="nomic-embed-text", host="http://172.30.160.1:11434")

# define the schema
class DecompilationPair(LanceModel):
    # This stores the ASM. 'SourceField' tells LanceDB to vectorize this text.
    asm_code: str = model.SourceField()
    # This stores the C. We don't necessarily need to vectorize the C, 
    # just retrieve it as a "Payload".
    c_code: str
    # The vector itself (automatically generated by LanceDB using nomic)
    vector: Vector(model.ndims()) = model.VectorField()

# table = db.create_table("code_samples", schema=CodeChunks, mode="overwrite")
# table.add([
#     {"text": "print('hello world!')", "filename": "hello.py"},
#     {"text": "print('goodbye world!')", "filename": "goodbye.py"}
# ])

# create the table
db = lancedb.connect("ragdb")
table = db.create_table("code_samples", schema=DecompilationPair, mode="overwrite")
table.add(code_samples)

# table.add([{"asm_code": "...", "c_code": "...", "function_name": "sub_123"}])

# 1. Create an empty list
#reconstruction_batch = []
# 2. Loop through your files/sections and add to the list
# for asm_file, c_file in your_matching_logic:
#     reconstruction_batch.append({
#         "asm_code": load_asm(asm_file),
#         "c_code": load_c(c_file),
#         "function_name": "sub_1234"
#     })
# 
# # 3. Add the WHOLE list at once
# table.add(reconstruction_batch)

# query = "greetings"
# actual = table.search(query).limit(1).to_pydantic(CodeChunks)[0]
# print(actual.text)
