#include "dos/instruction.h"

const InstructionClass INSTR_CLASS[] = {
//   0           1          2         3         4          5          6         7          8         9          A          B          C          D         E        F
INS_ADD,     INS_ADD,   INS_ADD,  INS_ADD,   INS_ADD,   INS_ADD,  INS_PUSH,   INS_POP,   INS_OR,   INS_OR,    INS_OR,    INS_OR,    INS_OR,    INS_OR,  INS_PUSH, INS_NONE,  // 0
INS_ADC,     INS_ADC,   INS_ADC,  INS_ADC,   INS_ADC,   INS_ADC,  INS_PUSH,   INS_POP,  INS_SBB,  INS_SBB,   INS_SBB,   INS_SBB,   INS_SBB,   INS_SBB,  INS_PUSH,  INS_POP,  // 1
INS_AND,     INS_AND,   INS_AND,  INS_AND,   INS_AND,   INS_AND,  INS_NONE,   INS_DAA,  INS_SUB,  INS_SUB,   INS_SUB,   INS_SUB,   INS_SUB,   INS_SUB,  INS_NONE,  INS_DAS,  // 2
INS_XOR,     INS_XOR,   INS_XOR,  INS_XOR,   INS_XOR,   INS_XOR,  INS_NONE,   INS_AAA,  INS_CMP,  INS_CMP,   INS_CMP,   INS_CMP,   INS_CMP,   INS_CMP,  INS_NONE,  INS_AAS,  // 3
INS_INC,     INS_INC,   INS_INC,  INS_INC,   INS_INC,   INS_INC,   INS_INC,   INS_INC,  INS_DEC,  INS_DEC,   INS_DEC,   INS_DEC,   INS_DEC,   INS_DEC,   INS_DEC,  INS_DEC,  // 4
INS_PUSH,   INS_PUSH,  INS_PUSH, INS_PUSH,  INS_PUSH,  INS_PUSH,  INS_PUSH,  INS_PUSH,  INS_POP,  INS_POP,   INS_POP,   INS_POP,   INS_POP,   INS_POP,   INS_POP,  INS_POP,  // 5
INS_NONE,   INS_NONE,  INS_NONE, INS_NONE,  INS_NONE,  INS_NONE,  INS_NONE,  INS_NONE, INS_NONE, INS_NONE,  INS_NONE,  INS_NONE,  INS_NONE,  INS_NONE,  INS_NONE, INS_NONE,  // 6
INS_JMP,     INS_JMP,   INS_JMP,  INS_JMP,   INS_JMP,   INS_JMP,   INS_JMP,   INS_JMP,  INS_JMP,  INS_JMP,   INS_JMP,   INS_JMP,   INS_JMP,   INS_JMP,   INS_JMP,  INS_JMP,  // 7
INS_NONE,   INS_NONE,  INS_NONE, INS_NONE,  INS_TEST,  INS_TEST,  INS_XCHG,  INS_XCHG,  INS_MOV,  INS_MOV,   INS_MOV,   INS_MOV,   INS_MOV,   INS_LEA,   INS_MOV,  INS_POP,  // 8
INS_NOP,    INS_XCHG,  INS_XCHG, INS_XCHG,  INS_XCHG,  INS_XCHG,  INS_XCHG,  INS_XCHG,  INS_CBW,  INS_CWD,  INS_CALL,  INS_WAIT, INS_PUSHF,  INS_POPF,  INS_SAHF, INS_LAHF,  // 9
INS_MOV,     INS_MOV,   INS_MOV,  INS_MOV, INS_MOVSB, INS_MOVSW, INS_CMPSB, INS_CMPSW, INS_TEST, INS_TEST, INS_STOSB, INS_STOSW, INS_LODSB, INS_LODSW, INS_SCASB, INS_SCASW, // A
INS_MOV,     INS_MOV,   INS_MOV,  INS_MOV,   INS_MOV,   INS_MOV,   INS_MOV,   INS_MOV,  INS_MOV,  INS_MOV,   INS_MOV,   INS_MOV,   INS_MOV,   INS_MOV,   INS_MOV,   INS_MOV, // B
INS_NONE,   INS_NONE,   INS_RET,  INS_RET,   INS_LES,   INS_LDS,   INS_MOV,   INS_MOV, INS_NONE, INS_NONE,  INS_RETF,  INS_RETF,   INS_INT,   INS_INT,  INS_INTO,  INS_IRET, // C
INS_NONE,   INS_NONE,  INS_NONE, INS_NONE,   INS_AAM,   INS_AAD,  INS_NONE,  INS_XLAT, INS_NONE, INS_NONE,  INS_NONE,  INS_NONE,  INS_NONE,  INS_NONE,  INS_NONE,  INS_NONE, // D
INS_LOOPNZ, INS_LOOPZ, INS_LOOP, INS_JCXZ,    INS_IN,    INS_IN,   INS_OUT,   INS_OUT, INS_CALL,  INS_JMP,   INS_JMP,   INS_JMP,    INS_IN,    INS_IN,   INS_OUT,   INS_OUT, // E
INS_LOCK,   INS_NONE, INS_REPNZ, INS_REPZ ,  INS_HLT,   INS_CMC,  INS_NONE,  INS_NONE,  INS_CLC,  INS_STC,   INS_CLI,   INS_STI,   INS_CLD,   INS_STD,  INS_NONE,  INS_NONE, // F
};

InstructionClass instr_class(const Byte opcode) {
    return INSTR_CLASS[opcode];
}
