name: C++ CI Build

on:
  push:
    branches: [ master,main ]
  pull_request:
    branches: [ master,main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build Project
      run: ./build.sh
